### ISSUE TITLE
Bug: Buttercup removes function calls with possible side effects

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#101]
Buttercup removes function calls assigned to an unused variable, not knowing whether the function has any side effects.

This code squashed will call `sideEffected()`:
```javascript
function fn () {
  sideEffected()
}
```

But this won't:

```javascript
function fn () {
  var unused = sideEffected()
}
```

**Comment by Loilo** [comment]
Side note: The unused variable itself may still very well be removed. It should be fine to just keep the function call.

**Comment by Loilo** [comment]
Generally best compression would be achieved by only extracting function calls from such statements.

But that might be an overly complicated task for what might be considered an edge case.

**Comment by Rich-Harris** [comment]
@Loilo currently working on this, and trying to figure out the best approach. It's certainly preferable to omit the variable and only include the function ID if possible. For a standalone var declaration it ought to be fairly straightforward — it gets a little hairier when you have multiple declarations, or multiple declarators per declaration, and the side-effecty inits are nestled somewhere within:

```js
(function () {
  var a = 1;
  var b = x();
  var c = 3;
  var d = 4;

  console.log( a, c, d );
}());
```

Uglify does this, to avoid having to repeat the `var` keyword after `x()`:

```js
!function(){var a=1,c=(x(),3),d=4;console.log(a,c,d)}();
```

Which is very clever! Might settle for this to begin with, as it's only two extra bytes:

```js
!function(){var a=1;x();var c=3,d=4;console.log(a,c,d)}();
```

**Comment by Loilo** [comment]
That's in fact really clever.

Another really edge-casey thing that Uglify does very smart:

```javascript
(function () {
  var b = x() ? y() : y();
}());
```

will transpile to

```javascript
!function(){x(),y()}();
```
