### ISSUE TITLE
Error: Cannot overwrite a zero-length range

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#111]
I tried to squash another minified library, namely [abcjs](https://cdnjs.cloudflare.com/ajax/libs/abcjs/3.1.1/abcjs_basic-min.js).

This one doesn't even mourn about invalid generated code, it doesn't minify at all.

* Error: `Cannot overwrite a zero-length range – use insertLeft or insertRight instead`
* Saved Buttercup: [see here](https://butternut.now.sh/?version=0.4.4&gist=06b8e4edfa4741b5e757a7b8f21726d3)

**Comment by Rich-Harris** [comment]
There a few different things going on here — fixed by #114
