### ISSUE TITLE
Bug: Combinations of braceless if and switch blocks are not handled correctly

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#113]
Squashing the minified [Ace Editor](https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js) failed.

Butternut did not handle the following minimal situation correctly:

```javascript
if ( any_condition )
  switch ( any_value ) {
    case '':
  }
else {
  do_something()
}
```

This generates the following output:
```javascript
if(any_condition)switch(any_value){case '':};else do_something()
```

The problem is, that the semi-colon after the `switch` block is in fact invalid syntax.

For reference: UglifyJS just does not insert the semi-colon, that's it.

**Comment by Rich-Harris** [comment]
Thanks — this was fixed by https://github.com/Rich-Harris/butternut/commit/0fdfa3fb42298c9edc6be601cdc166a0ccb12efd, release soon
