### ISSUE TITLE
Bug: IIFE exclamation marks are incorrectly removed inside conditions

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#117]
Trying to squash minified [aight](https://cdnjs.cloudflare.com/ajax/libs/aight/1.2.2/aight.min.js) failed.

The essence is that IIFEs in the form of `!function() { ... }()` that are evaluated as conditions will fail incorrectly get their exclamation mark removed by Butternut, resulting in invalid output:

```javascript
function fn () {
  if ( !function () {
    return any_value
  }() ) {
    do_something()
  }
}
```

The invaild output is this:
```javascript
function fn(){function(){return any_value}()||do_something()}
```

**Comment by Rich-Harris** [comment]
thanks, fixed — will work through the other bugs before cutting a release
