### ISSUE TITLE
Bug: Parantheses around new Function constructor are removed

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#118]
Trying to squash minified [ajile](https://cdnjs.cloudflare.com/ajax/libs/ajile/2.1.7/com.iskitz.ajile.js), I noticed the following:

Butternut removes parantheses around the `new Function` constructor.

This can be critical in the following situation:

```javascript
(function () {
  return (new Function("return any_value;"))()
})()
```

This will be evaluated to the following invalid output:
```javascript
!function(){returnnew Function("return any_value;")()}()
```

**Comment by Loilo** [comment]
I'll happily test more libraries as soon as the current issues are fixed since I keep running into the same ones—especially #109 and #113 are pretty common. :)

**Comment by Rich-Harris** [comment]
Turns out this is already fixed in master (as a byproduct of other fixes) — will cut a release

**Comment by Loilo** [comment]
Great! Let's see if that lowers the frequency of failure in my script which tests Butternut on [all the libraries](https://api.cdnjs.com/libraries) from cdnjs. 😁

**Comment by Rich-Harris** [comment]
Woah, that's a great idea. We should build that into this repo!

**Comment by Loilo** [comment]
I currently have it as a private repo on GitHub. I'll do some polishing later today and will then make it public.
