### ISSUE TITLE
Bug: Numbers with attached methods

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#126]
Error from squashing the minified [aight](https://cdnjs.cloudflare.com/ajax/libs/aight/1.2.2/aight.min.js) source.

Long story short: Butternut rewrites non-decimals to decimals. If there were method calls on the non-decimals (without surrounding parantheses), they will be kept. This leads to invalid syntax.

**Input:**
```javascript
0x0.toFixed()
```

**Output Butternut:**
```javascript
0.toFixed()
```

**Output UglifyJS:**
```javascript
0..toFixed()
```

EDIT: It's actually not just non-decimals. Numbers in general get their necessary surroundings removed:

**Input:**
```javascript
(1).toFixed()
```

**Output Butternut:**
```javascript
1.toFixed()
```

**Output UglifyJS:**
```javascript
1..toFixed()
```

**Comment by loilo** [comment]
This still occurs with negative numbers.

### Basic example

**Input:**
```javascript
(-2).toFixed()
```

**Output Butternut 0.4.6:**
```javascript
(-2)..toFixed()
```

**Output UglifyJS 3.0.8:**
```javascript
(-2).toFixed();
```

### Example with extended `Number` prototype
As used in [Turf.js](https://cdnjs.cloudflare.com/ajax/libs/Turf.js/4.3.1/turf.min.js).

**Input:**
```javascript
(-2).toRadians()
```

**Output Butternut 0.4.6:**
```javascript
-2.toRadians()
```

**Output UglifyJS 3.0.8:**
```javascript
(-2).toRadians();
```
