### ISSUE TITLE
"linebreak-style" eslint rule is a footgun on Windows

### ISSUE THREAD

**Issue by RReverser** [Rich-Harris/butternut#13]
Freshly cherry-picked repo is full of warnings about incorrect line endings in the repo.

This is because Git by default checks out text files with native line endings (CR LF) and commits back with normalised to LF.

If you want to enforce specific line endings even on user's copy of the repo, the usual way to fix this is to add `.gitattributes` which can tell Git to always check out with preferred line endings instead of using native ones on the target.

However, in this case, `test/fixture/input/Rx.js` needs to have all line endings changed too (seems that they're currently CR LF even in the repo).

An alternative would be to add `.gitattributes` which ensures that line endings are always correctly converted (`text=auto`) and to remove ESLint rule.

In either case, it would be nice to have this fixed so that devs on Windows could contribute too 😄 Just let me know which approach sounds better to you.

**Comment by Rich-Harris** [comment]
merged #14, closing — thanks
