### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by flagello** [Rich-Harris/butternut#15]
Just saw [Rich-Harris/butternut.now.sh](https://github.com/Rich-Harris/butternut.now.sh) in my feed and immediately went to check what it was about.

On behalf of every sentient human being on Earth, thank you Rich for all the impressive work and thought you put into every repo you open on GitHub or [GitLab](https://gitlab.com/Rich-Harris/buble).

Hopefully I'm not over-reacting _(or should I say over-svelting to avoid runtime overhead?)_ here, but it seems to me that your work is consistently of the highest quality, usefulness, and intention, and like so, it deserves continuous praise and encouragement.

May it never be enough! Thank you!

**Comment by rob-balfre** [comment]
100% what @flagello said! 👏

**Comment by Rich-Harris** [comment]
Thank you both! It makes a huge difference knowing that the work is useful and appreciated, and I'm grateful that you took time out of your day to say so.
