### ISSUE TITLE
Bug: Nested empty conditions

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#164]
Butternut hiccups on nested `if` blocks with no statements inside.

**Input:**
```javascript
if ( any_condition_1 ) {
  if ( any_condition_2 ) {

  }
}
```

**Output Butternut 0.4.6:**
```javascript
any_condition_1&&()
```

**Output UglifyJS 3.0.8:**
```javascript
any_condition_1&&any_condition_2;
```

**Comment by nifgraup** [comment]
duplicates #127

**Comment by loilo** [comment]
That's right. Closing in favor of #127 then.
