### ISSUE TITLE
Renaming function arguments doesn't play well with ES6 object shorthand

### ISSUE THREAD

**Issue by RyanZim** [Rich-Harris/butternut#167]
Input:
```js
function foo (a, b) {
  return {a, b}
}
```

Expected Output:
```js
function foo(a,b){return {a,b}}
```

Actual Output:
```js
function foo(n,r){return{a:n,b:r}}
```

This is wasting bytes. Don't know if this is common enough in real-world code to optimize, but just thought I'd point it out.

**Comment by Conduitry** [comment]
This has already come up in #72 but it might still make sense to have a narrower ticket just for this issue.

**Comment by RyanZim** [comment]
Ah, sorry. Didn't see that issue.

> I think shorthand properties is (currently) the only place where this could happen

So I think I'll close this.
