### ISSUE TITLE
squash fails with THREE.OrbitControls.js

### ISSUE THREAD

**Issue by backspaces** [Rich-Harris/butternut#175]
To reproduce, 
curl https://unpkg.com/three@0.85.2/examples/js/controls/OrbitControls.js > foo.js

Then try either putting in the REPL or simply use `squash foo.js > foo.min.js`
The former works but suspiciously small. The latter completes but prints a warning: 
```
The final argument to magicString.overwrite(...) should be an options object.
See https://github.com/rich-harris/magic-string
```

Finally using `squash --check foo.js > foo.min.js` is hangs.

Converting to uglify-es worked so I'm pretty sure this is a bug.

**Comment by nifgraup** [comment]
duplicate of #172 ?

**Comment by nifgraup** [comment]
can not reproduce on master

**Comment by backspaces** [comment]
Works now, don't know what changed.

**Comment by backspaces** [comment]
Oops. I still get the error message 
> The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string

But the minified files exist and appear to work correctly.

This is not an OrbitControls.js issue now, but when I minify my dual repo: <script> and es6 Module rollups:
`squash dist/AS.js > dist/AS.min.js && squash dist/AS.module.js > dist/AS.module.min.js`

**Comment by backspaces** [comment]
Lets close, looks like duplicate of #172
