### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by albertosantini** [Rich-Harris/butternut#184]
Since `0.4.5` included (so also `0.4.6`) I get the error message in the title, when I try to minimize a bundle created with rollup. With `0.4.4` it is ok.

Steps to reproduce the issue:
- clone the repo https://github.com/albertosantini/argo
- change `butternut` version in `package.json` (now fixed to `0.4.4`)
- $ npm install
- $ npm run rollup-d3
- $ npm test

```
...
> argo-trading@5.0.2 karma C:\My\Dev\argo-trading\argo
> karma start --single-run

15 07 2017 10:31:13.392:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
15 07 2017 10:31:13.408:INFO [launcher]: Launching browser Chrome with unlimited concurrency
15 07 2017 10:31:13.408:INFO [launcher]: Starting browser Chrome
15 07 2017 10:31:15.143:INFO [Chrome 59.0.3071 (Windows 10 0.0.0)]: Connected on socket BAo4auD6DJ0732uvAAAA wi
th id 25387013
Chrome 59.0.3071 (Windows 10 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token (
  at build/d3-techan.min.js:1
```

(Using the unminified version of the file, the tests pass).

**Comment by nifgraup** [comment]
Notice that there is already an error during the `npm run rollup-d3` step. Duplicate of #172, can not reproduce on master.

**Comment by albertosantini** [comment]
I would say it is fixed with the latest versions. 
Thanks for the effort.
