### ISSUE TITLE
Why are inline sourcemaps not recommended?

### ISSUE THREAD

**Issue by jamen** [Rich-Harris/butternut#189]
Hey, awesome library.  Can't wait to try this in my stuff.

I saw you mention in the [JavaScript API section]() that inline sourcemap is discouraged:

> Whether to create a sourcemap. Set to `inline` to append to the output (not recommended)

Can you elaborate?  I know `browserify` does inline sourcemaps and I haven't had trouble with these.

**Comment by marijnh** [comment]
I suspect the thought behind that note is that if you're minifying, you probably care about file size, and dumping an inline source map into your file is _not_ going to help with that, as it'll likely add more size than you save with the minification to begin with.

**Comment by jamen** [comment]
Okay, that's fair.  Thanks!
