### ISSUE TITLE
uglify-es

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/butternut#2]
> Unfortunately, the most popular minifier — UglifyJS — doesn't officially support ES2015. 

Official ES2015 version of Uglify as of an hour ago:

https://www.npmjs.com/package/uglify-es

**Comment by Rich-Harris** [comment]
Yeah I *just* saw that. Dammit!

**Comment by kzc** [comment]
Make no mistake - it's also alpha quality and chock-full-o-bugs. But it's an *official* package!

**Comment by Rich-Harris** [comment]
Have updated the README, so I'll close this
