### ISSUE TITLE
Body-less loop with semicolon as last line in block

### ISSUE THREAD

**Issue by Conduitry** [Rich-Harris/butternut#38]
If you have a loop (`for`, `while`) that is body-less and is terminated with a semicolon (rather than braces), and it's the last line in its block, the semicolon is removed, resulting in invalid code.

```javascript
function f() {
  while (g());
}
```

produces

```javascript
function f(){while(g())}
```

which is invalid. [REPL](https://butternut.now.sh/?version=0.3.5&gist=4cb31cb46984e8de2954b18d97593708), although its use of `check: true` prevents you from actually seeing this output.

**Comment by Rich-Harris** [comment]
Good catch. Yeah, the `check: true` option should probably include the resulting broken code on the error object so we can still show the output, that's annoying

**Comment by Rich-Harris** [comment]
[Fixed in 0.3.6](https://butternut.now.sh/?version=0.3.6&gist=4cb31cb46984e8de2954b18d97593708), thanks
