### ISSUE TITLE
`[].slice || ...` generates broken code

### ISSUE THREAD

**Issue by jbt** [Rich-Harris/butternut#54]
Looks like `[].slice || (...anything)` gets replaced with emptystring. 

For example: `[].slice||1; 1` becomes `,1`  ([link](https://butternut.now.sh/?version=0.3.6&gist=ec465a5cfe4eeed025a57f90affb7614))

A less contrived example: `var slice = [].slice || function() {...}, somethingElse = 1;` becomes `var slice=,somethingElse=1` ([link](https://butternut.now.sh/?version=0.3.6&gist=429aec86c1646726e5840adc052cb35a))

Seems to happen with `.slice` and other array methods like `indexOf`, but not for any old property (i.e. `[].foo` is fine)

**Comment by Rich-Harris** [comment]
Released 0.4 with the fix, thanks
