### ISSUE TITLE
Non-empty loops being collapsed if first node is EmptyStatement

### ISSUE THREAD

**Issue by jbt** [Rich-Harris/butternut#57]
e.g. `while (a) { ; b(); }` -> `while(a);;` ([link](https://butternut.now.sh/?version=0.3.6&gist=e75610922f15388d5846ab270aa2dcb4))

I tried making some [test-cases + fixing up the check for empty nodes](https://github.com/jbt/butternut/commit/629c560b61cc5e8266a8eff2d75c1164f4b1b17c) by checking over every descendent node rather than just the first, but my do-while case is failing completely for magic-string reasons I don't fully understand.

Additionally, all cases where a curly-braced loop _could_ be reduced to a single-statement body aren't working because I can't figure out how to trim leading/trailing `EmptyStatement`s. 

Incidentally it looks like there's a few more cases where leading empty statements in a block change the output (e.g. `if (a) { b(); }` vs `if (a) { ; b(); }`) but the loops are the only case where it's doing something it definitely shouldn't.

**Comment by Rich-Harris** [comment]
Thanks. It was operating under the incorrect assumption that if the first statement of the body was an EmptyStatement, the body itself was empty. It should really remove empty statements altogether — will get to that soon — but #59 generates correct if suboptimal code
