### ISSUE TITLE
Readme: How?

### ISSUE THREAD

**Issue by andywer** [Rich-Harris/butternut#7]
It would be nice if the README explained the most interesting part:
What does it do to support bleeding edge JS and yet be significantly faster than Uglify/Babili?

That might boost people's trust and confidence in the project. People like to know what a thing does :)

Plus: Might be worth to provide a small setup for benchmarking Butternut, Uglify and Babili minifying some files. So people can try it on their own machine, maybe run in the benchmark against their own files.

But a good job! This is really useful :)

**Comment by Rich-Harris** [comment]
Good idea! Have added a section to the README: https://github.com/Rich-Harris/butternut#how

You can run the benchmarks yourself with `npm run bench` inside this repo.
