### ISSUE TITLE
Cannot read property 'getRightHandSide' of undefined

### ISSUE THREAD

**Issue by jbt** [Rich-Harris/butternut#89]
From the following example:

```js
if (a) {
  if (b) {
    c;
  } else {
    // empty / comented out
  }
}
```

Coming from inside BlockStatement: https://github.com/Rich-Harris/butternut/blob/6f83a370a170bfd8b7793400c57bb9266e26a05f/src/program/BlockStatement.js#L112

Adding `if (this.body.length === 0) return this;` at the top of `BlockStatement`'s getLeft/RightHandSide seems to fix it up fine and tests all pass, not sure whether I'm missing something though.

**Comment by Rich-Harris** [comment]
fixed in 0.4.4, thanks
