### ISSUE TITLE
Minified angular-ui-bootstrap causes error

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#92]
I tried another minified source that threw an error. I'll probably try some more but but not put them all into the same issue since their errors may obviously be completely unrelated.

This time I tried minified *angular-ui-bootstrap* [from cdnjs](https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.0/ui-bootstrap-tpls.min.js). The saved Butternut is to be found [here](https://butternut.now.sh/?version=0.4.3&gist=663bc55910ef7a536e003711e4ed1578).

I tried to investigate a little more on my own with this one, but I just couldn't find invalid generated code anywhere. I could even put the code back into a prettifier (provided that the big code block posted to the console is the generated code?) and it wouldn't complain. So this might possibly also be an issue with the code checker.

**Comment by jbt** [comment]
I just came across what I believe is essentially the same issue - here `e=e!==!1` is getting minified to `e!===!1` - looks like there needs to be a whitelist of which binary operators can be converted to `a *= b`-type assignments. (my example was `a = a in b` -> `ain=b` which is quite fun)

I can make a PR with a whitelist of what assignment+binaryexpression combinations are safe to turn into single assignment operators.

**Comment by Rich-Harris** [comment]
Thanks — have released 0.4.4 with @jbt's fix, so this *might* work now... 😬

**Comment by Loilo** [comment]
Running the example [with 0.4.4](https://butternut.now.sh/?version=0.4.4&gist=663bc55910ef7a536e003711e4ed1578) works fine now, I think we can close this.

I'll try some more minified sources, they seem to be sources of great edge cases. 😁
